### ISSUE TITLE
Использование Partner API

### ISSUE THREAD

**Issue by Michael-Kr** [GrouponRussia/groupon-api#3]
Я хочу использовать Partner API для того чтобы получать список доступных Акций, рекламировать их в своем мобильном приложении и получать партнерские выплаты в Admitad. (ссылки для Акций буду строить с помощью инструмента deeplink в Admitad)
Я зарегистрировался на сайте Groupon, зарегистрировался в Admitad и получил разрешение на сотрудничество с Groupon в этой сети. Но как же мне получить право на пользование Partner API? (В данный момент при запросе на список Акций получаю Access Denied)

**Comment by alexeypanin** [comment]
Здравствуйте, пришлите нам на почту  ru-dev@groupon.com, email пользователя, под которым вы делаете запросы, ему необходимо предоставить соответствующую роль, после чего все заработает.
